server: 
  listen: 8000

  workers: 6

  forwards:
    - id: endpoint1
      url: https://jsonplaceholder.typicode.com

    - id: endpoint2
      url: https://jsonplaceholder.typicode.com/comments

    - id: endpoint3
      url: https://jsonplaceholder.typicode.com/todos

  headers:
    - key: x-forward-for
      value: $remote_addr

    - key: authorization
      value: "Bearer xyz"

  rules:
    - path: /
      forward: 
        - endpoint1
        - endpoint2

    - path: /test
      forward: 
        - endpoint3
      